export const themes = {
  wedding: {
    bg: "bg-stone-50",
    card: "bg-white",
    text: "text-stone-800",
    accent: "text-amber-600",
    button: "bg-amber-600 hover:bg-amber-700 text-white",
    border: "border-stone-200",
    font: "font-serif",
    icon: "text-amber-500",
  },
  birthday: {
    bg: "bg-sky-50",
    card: "bg-white",
    text: "text-slate-800",
    accent: "text-rose-500",
    button: "bg-rose-500 hover:bg-rose-600 text-white",
    border: "border-sky-100",
    font: "font-sans",
    icon: "text-rose-400",
  },
  graduation: {
    bg: "bg-indigo-50",
    card: "bg-white",
    text: "text-slate-900",
    accent: "text-indigo-700",
    button: "bg-indigo-700 hover:bg-indigo-800 text-white",
    border: "border-indigo-100",
    font: "font-sans",
    icon: "text-indigo-600",
  },
  other: {
    bg: "bg-slate-50",
    card: "bg-white",
    text: "text-slate-800",
    accent: "text-emerald-600",
    button: "bg-emerald-600 hover:bg-emerald-700 text-white",
    border: "border-slate-200",
    font: "font-sans",
    icon: "text-emerald-500",
  },
};
